//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication11.Models.EntityFramework
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DbMvcSchoolEntities : DbContext
    {
        public DbMvcSchoolEntities()
            : base("name=DbMvcSchoolEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tbl_clubs> tbl_clubs { get; set; }
        public virtual DbSet<tbl_lessons> tbl_lessons { get; set; }
        public virtual DbSet<tbl_notes> tbl_notes { get; set; }
        public virtual DbSet<tbl_students> tbl_students { get; set; }
    }
}
