//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication11.Models.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_students
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_students()
        {
            this.tbl_notes = new HashSet<tbl_notes>();
        }
    
        public int STUDENTID { get; set; }
        public string STUDENTNAME { get; set; }
        public string STUDENTSURNAME { get; set; }
        public string STUDENTPHOTO { get; set; }
        public string STUDENTGENDER { get; set; }
        public Nullable<byte> STUDENTCLUB { get; set; }
    
        public virtual tbl_clubs tbl_clubs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_notes> tbl_notes { get; set; }
    }
}
