//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication11.Models.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_notes
    {
        public int NOTEID { get; set; }
        public Nullable<int> LESSONID { get; set; }
        public Nullable<int> STUDENTID { get; set; }
        public Nullable<byte> EXAM1 { get; set; }
        public Nullable<byte> EXAM2 { get; set; }
        public Nullable<byte> EXAM3 { get; set; }
        public Nullable<byte> PROJECT { get; set; }
        public Nullable<decimal> AVERAGE { get; set; }
        public Nullable<bool> STATUS { get; set; }
    
        public virtual tbl_lessons tbl_lessons { get; set; }
        public virtual tbl_students tbl_students { get; set; }
    }
}
